/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.launcher;

import java.awt.BorderLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author emman
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
       
        Simulators simulators = new Simulators();
        simulators.setSize(1550,870);
        simulators.setLocation(0,0);
        
        Content.removeAll();
        Content.add(simulators, BorderLayout.CENTER);
        Content.revalidate();
        Content.repaint();
        
         // Centra la ventana en la pantalla.
        this.setLocationRelativeTo(this);
        
        // Nombre base para las imágenes de los botones.
        String imageName = "LauncherButton";
        
        // Nombres de los botones en el formulario.
        String[] buttons = {
            "Button0", "Button1", "Button2", "Button3", "Button4",
            "Button5", "Button6", "Button7", "Button8", "Button9", 
            "Button10", "Button11", "Button12", "Button13"
        };
        System.out.println("un papiii cambiooo");
        
        // Itera sobre los nombres de los botones.
        for (int i = 0; i < buttons.length; i++) {
            
            // Construye la ruta de la imagen para el botón actual.
            String image = "src/icons/" + imageName + i + ".png";
            
            try {
                // Obtiene la etiqueta JLabel correspondiente al botón actual.

                javax.swing.JLabel buttonLabel = (javax.swing.JLabel) getClass().getDeclaredField(buttons[i]).get(this);
                
                // Asigna la imagen al botón usando la librería RSScaleLabel.
                rsscalelabel.RSScaleLabel.setScaleLabel(buttonLabel, image);
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al cargar la imagen: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
            
        }

        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        contenedorBtns = new javax.swing.JPanel();
        Button0 = new javax.swing.JLabel();
        Button1 = new javax.swing.JLabel();
        Button2 = new javax.swing.JLabel();
        Button3 = new javax.swing.JLabel();
        Button4 = new javax.swing.JLabel();
        Button5 = new javax.swing.JLabel();
        Button6 = new javax.swing.JLabel();
        Button7 = new javax.swing.JLabel();
        Button8 = new javax.swing.JLabel();
        Button9 = new javax.swing.JLabel();
        Button10 = new javax.swing.JLabel();
        Button11 = new javax.swing.JLabel();
        Button12 = new javax.swing.JLabel();
        Button13 = new javax.swing.JLabel();
        Content = new javax.swing.JPanel();
        fondoUniversae = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMaximumSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contenedorBtns.setOpaque(false);
        contenedorBtns.setLayout(new java.awt.GridLayout(1, 14, 20, 40));

        Button0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/launcher/LauncherButton1.png"))); // NOI18N
        contenedorBtns.add(Button0);

        Button1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/launcher/LauncherButton1.png"))); // NOI18N
        Button1.setMaximumSize(new java.awt.Dimension(80, 80));
        Button1.setMinimumSize(new java.awt.Dimension(80, 80));
        contenedorBtns.add(Button1);

        Button2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/launcher/LauncherButton1.png"))); // NOI18N
        contenedorBtns.add(Button2);

        Button3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/launcher/LauncherButton1.png"))); // NOI18N
        contenedorBtns.add(Button3);

        Button4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/launcher/LauncherButton1.png"))); // NOI18N
        contenedorBtns.add(Button4);

        Button5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/launcher/LauncherButton1.png"))); // NOI18N
        contenedorBtns.add(Button5);

        Button6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/launcher/LauncherButton1.png"))); // NOI18N
        contenedorBtns.add(Button6);

        Button7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/launcher/LauncherButton1.png"))); // NOI18N
        contenedorBtns.add(Button7);

        Button8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/launcher/LauncherButton1.png"))); // NOI18N
        contenedorBtns.add(Button8);

        Button9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/launcher/LauncherButton1.png"))); // NOI18N
        contenedorBtns.add(Button9);

        Button10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/launcher/LauncherButton1.png"))); // NOI18N
        contenedorBtns.add(Button10);

        Button11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/launcher/LauncherButton1.png"))); // NOI18N
        Button11.setPreferredSize(new java.awt.Dimension(50, 50));
        contenedorBtns.add(Button11);

        Button12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/launcher/LauncherButton1.png"))); // NOI18N
        contenedorBtns.add(Button12);

        Button13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/launcher/LauncherButton1.png"))); // NOI18N
        contenedorBtns.add(Button13);

        jPanel1.add(contenedorBtns, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 1500, 90));

        Content.setOpaque(false);

        javax.swing.GroupLayout ContentLayout = new javax.swing.GroupLayout(Content);
        Content.setLayout(ContentLayout);
        ContentLayout.setHorizontalGroup(
            ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1550, Short.MAX_VALUE)
        );
        ContentLayout.setVerticalGroup(
            ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 870, Short.MAX_VALUE)
        );

        jPanel1.add(Content, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 1550, 870));

        fondoUniversae.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/launcher/FondoBase.png"))); // NOI18N
        fondoUniversae.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fondoUniversae.setMaximumSize(new java.awt.Dimension(1920, 1080));
        fondoUniversae.setMinimumSize(new java.awt.Dimension(0, 0));
        fondoUniversae.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jPanel1.add(fondoUniversae, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Button0;
    private javax.swing.JLabel Button1;
    private javax.swing.JLabel Button10;
    private javax.swing.JLabel Button11;
    private javax.swing.JLabel Button12;
    private javax.swing.JLabel Button13;
    private javax.swing.JLabel Button2;
    private javax.swing.JLabel Button3;
    private javax.swing.JLabel Button4;
    private javax.swing.JLabel Button5;
    private javax.swing.JLabel Button6;
    private javax.swing.JLabel Button7;
    private javax.swing.JLabel Button8;
    private javax.swing.JLabel Button9;
    private javax.swing.JPanel Content;
    private javax.swing.JPanel contenedorBtns;
    private javax.swing.JLabel fondoUniversae;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
